dataset_dir: /home/yukan/Documents/work/lane_mapping/lane3d_dataset/

preprocess:
  downsample_distance: 0.5

lane_mapping:
  ctrl_points_chord: 3.0
  candidate_angle_thresh: 90
  sliding_window_size: 7